name: Build Userscript

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build script
        run: node build/build.js

      - name: Commit dist
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add dist
          git commit -m "auto build" || echo "no changes"
          git push